### ISSUE TITLE
Result tidak berubah

### ISSUE THREAD

**Issue by Saepulawr** [mncinnovation/mnc_identifier_face#2]
Halo dev,
saya ketemu bug mungkin ya,
saat selesai capture dan dapat resultnya.
image result nya selalu sama dengan result image result yg pertama kali capture.
walaupun sudah beberapa kali coba,hasil gambarnya tetap sama.
bahkan sudah saya coba hapus file image sebelumnya. di saat melakukan capture lagi,result nya image nya kembali sama dengan result yg pertama kali.

**Comment by vivek03codes** [comment]
@Saepulawr Did you find the solution for this?
